# Generated by tools/jitgen.py: no blocks. A -d:nds_jit build includes this
# file unless -d:nds_jit_gen=PATH names a generated one (docs/nds/jit.md).
template jit_blocks9*(B: typedesc): untyped = newSeq[(uint32, JitFn[B])]()
template jit_blocks7*(B: typedesc): untyped = newSeq[(uint32, JitFn[B])]()
