@ waitprobe.s — does an EMPTY cartridge slot still honour WAITCNT?
@
@ The control for running hdmasweep.s over the link rig: that page's loop
@ leans on a 32-bit load from 0x08000000 taking its configured eight waits,
@ and the rig multiboots with no cartridge in the slot. Wait states are
@ generated by the memory controller rather than the cartridge, so the access
@ should still take its time, but that is reasoning, and this measures it.
@
@ r0 in:  bits 0-15  the WAITCNT value to test
@         bit 16     set = time 16-bit loads (ldrh) instead of 32-bit (ldr)
@ r0 out: TM0 ticks for 256 loads from 0x08000000, prescaler 1
@
@ Read it as: sweep WAITCNT WS0 over 0x0000 (4 waits), 0x0004 (3), 0x0008 (2)
@ and 0x000C (8), prefetch off in all four. If the empty slot honours the
@ setting, the per-load cost tracks it — 32-bit is N+S, so 8/6/5/12 cycles
@ against a fixed ~6-cycle loop overhead, i.e. roughly 1024 ticks between the
@ 0x000C and 0x0000 runs. If the slot ignores WAITCNT, all four totals match
@ and hdmasweep's ROM rows do NOT mean what its header says.
@
@ Leaves WAITCNT and TM0 as it found them, and never touches IME.
    .arm
    .text
    .global _start
_start:
    push {r4-r8, lr}
    ldr r1, =0x04000204
    ldrh r8, [r1]                  @ WAITCNT as we found it
    mov r2, r0, lsr #16            @ halfword flag
    bic r0, r0, #0x10000
    strh r0, [r1]
    ldr r3, =0x08000000
    ldr r4, =0x04000100            @ TM0
    mov r5, #0
    str r5, [r4]                   @ stop TM0, reload 0
    mov r5, #0x80
    strh r5, [r4, #2]              @ start, prescaler 1 (one tick per cycle)
    mov r6, #256
    tst r2, #1
    bne 2f
1:  ldr r7, [r3]                   @ 32-bit load from the gamepak region
    subs r6, r6, #1
    bne 1b
    b   3f
2:  ldrh r7, [r3]                  @ 16-bit load from the gamepak region
    subs r6, r6, #1
    bne 2b
3:  ldrh r0, [r4]                  @ elapsed ticks
    mov r5, #0
    str r5, [r4]                   @ stop TM0
    strh r8, [r1]                  @ WAITCNT back
    pop {r4-r8, pc}
    .ltorg
