#!/bin/sh
# Assemble the DS HLE BIOS guest code (src/dingbat/nds/hle_bios.s) for both
# CPUs and regenerate src/dingbat/nds/hle_bios_image.nim, which embeds the
# bytes. Needs GNU binutils for arm-none-eabi (Homebrew
# arm-none-eabi-binutils, or devkitARM) and python3. Run after editing the
# .s; the emulator itself never assembles anything.
#
#   tools/nds_hle_bios.sh
set -eu
cd "$(dirname "$0")/.."
src=src/dingbat/nds/hle_bios.s
out=src/dingbat/nds/hle_bios_image.nim
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

for cpu in 9 7; do
  if [ $cpu = 9 ]; then arch=armv5te; flag=1; base=0xFFFF0000; else arch=armv4t; flag=0; base=0; fi
  arm-none-eabi-as -march=$arch --defsym ARM9=$flag -o "$tmp/bios$cpu.o" "$src"
  arm-none-eabi-ld -Ttext=$base -e _start -o "$tmp/bios$cpu.elf" "$tmp/bios$cpu.o"
  arm-none-eabi-objcopy -O binary "$tmp/bios$cpu.elf" "$tmp/bios$cpu.bin"
done

python3 - "$tmp" "$out" <<'EOF'
import sys
tmp, out = sys.argv[1], sys.argv[2]
lines = [
    "## GENERATED by tools/nds_hle_bios.sh from hle_bios.s -- do not edit.",
    "## The HLE BIOS's guest code for each CPU (see hle_bios.s), placed at the",
    "## start of the synthesized BIOS image; hle_bios.nim fills the rest.",
    "",
]
for cpu in ("9", "7"):
    data = open(f"{tmp}/bios{cpu}.bin", "rb").read()
    lines.append(f"const HLE_BIOS{cpu}_CODE* = [")
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}'u8" for b in data[i:i + 16])
        lines.append(f"  {row},")
    lines.append("]")
    lines.append("")
open(out, "w").write("\n".join(lines))
EOF
echo "wrote $out"
