#!/usr/bin/env python3
"""Build msrthumb.gba - the MSR T-bit pipeline probe test ROM.

Generates the 8x8 font include, assembles msrthumb.s, and writes a ROM with a
valid GBA cartridge header (Nintendo logo + complement check) so it boots on
real hardware and on flashcarts.

Usage:  python3 tests/roms/msrthumb_build.py
Needs:  arm-none-eabi-as, arm-none-eabi-objcopy, arm-none-eabi-objdump
"""

import hashlib
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Font: 8x8 cell, 5x7 glyphs. 1bpp, one byte per row, bit7 = leftmost pixel.
# ---------------------------------------------------------------------------
GLYPHS = {
    ' ': ["     ", "     ", "     ", "     ", "     ", "     ", "     "],
    '-': ["     ", "     ", "     ", "#####", "     ", "     ", "     "],
    '.': ["     ", "     ", "     ", "     ", "     ", "  ## ", "  ## "],
    ':': ["     ", " ##  ", " ##  ", "     ", " ##  ", " ##  ", "     "],
    '+': ["     ", "  #  ", "  #  ", "#####", "  #  ", "  #  ", "     "],
    '/': ["    #", "   # ", "   # ", "  #  ", " #   ", " #   ", "#    "],
    '?': [" ### ", "#   #", "    #", "   # ", "  #  ", "     ", "  #  "],
    '=': ["     ", "     ", "#####", "     ", "#####", "     ", "     "],
    '0': [" ### ", "#   #", "#  ##", "# # #", "##  #", "#   #", " ### "],
    '1': ["  #  ", " ##  ", "  #  ", "  #  ", "  #  ", "  #  ", " ### "],
    '2': [" ### ", "#   #", "    #", "   # ", "  #  ", " #   ", "#####"],
    '3': ["#####", "   # ", "  #  ", "   # ", "    #", "#   #", " ### "],
    '4': ["   # ", "  ## ", " # # ", "#  # ", "#####", "   # ", "   # "],
    '5': ["#####", "#    ", "#### ", "    #", "    #", "#   #", " ### "],
    '6': ["  ## ", " #   ", "#    ", "#### ", "#   #", "#   #", " ### "],
    '7': ["#####", "    #", "   # ", "  #  ", " #   ", " #   ", " #   "],
    '8': [" ### ", "#   #", "#   #", " ### ", "#   #", "#   #", " ### "],
    '9': [" ### ", "#   #", "#   #", " ####", "    #", "   # ", " ##  "],
    'A': [" ### ", "#   #", "#   #", "#####", "#   #", "#   #", "#   #"],
    'B': ["#### ", "#   #", "#   #", "#### ", "#   #", "#   #", "#### "],
    'C': [" ### ", "#   #", "#    ", "#    ", "#    ", "#   #", " ### "],
    'D': ["###  ", "#  # ", "#   #", "#   #", "#   #", "#  # ", "###  "],
    'E': ["#####", "#    ", "#    ", "#### ", "#    ", "#    ", "#####"],
    'F': ["#####", "#    ", "#    ", "#### ", "#    ", "#    ", "#    "],
    'G': [" ### ", "#   #", "#    ", "#  ##", "#   #", "#   #", " ####"],
    'H': ["#   #", "#   #", "#   #", "#####", "#   #", "#   #", "#   #"],
    'I': [" ### ", "  #  ", "  #  ", "  #  ", "  #  ", "  #  ", " ### "],
    'J': ["  ###", "   # ", "   # ", "   # ", "   # ", "#  # ", " ##  "],
    'K': ["#   #", "#  # ", "# #  ", "##   ", "# #  ", "#  # ", "#   #"],
    'L': ["#    ", "#    ", "#    ", "#    ", "#    ", "#    ", "#####"],
    'M': ["#   #", "## ##", "# # #", "# # #", "#   #", "#   #", "#   #"],
    'N': ["#   #", "##  #", "# # #", "#  ##", "#   #", "#   #", "#   #"],
    'O': [" ### ", "#   #", "#   #", "#   #", "#   #", "#   #", " ### "],
    'P': ["#### ", "#   #", "#   #", "#### ", "#    ", "#    ", "#    "],
    'Q': [" ### ", "#   #", "#   #", "#   #", "# # #", "#  # ", " ## #"],
    'R': ["#### ", "#   #", "#   #", "#### ", "# #  ", "#  # ", "#   #"],
    'S': [" ####", "#    ", "#    ", " ### ", "    #", "    #", "#### "],
    'T': ["#####", "  #  ", "  #  ", "  #  ", "  #  ", "  #  ", "  #  "],
    'U': ["#   #", "#   #", "#   #", "#   #", "#   #", "#   #", " ### "],
    'V': ["#   #", "#   #", "#   #", "#   #", "#   #", " # # ", "  #  "],
    'W': ["#   #", "#   #", "#   #", "# # #", "# # #", "## ##", "#   #"],
    'X': ["#   #", "#   #", " # # ", "  #  ", " # # ", "#   #", "#   #"],
    'Y': ["#   #", "#   #", " # # ", "  #  ", "  #  ", "  #  ", "  #  "],
    'Z': ["#####", "    #", "   # ", "  #  ", " #   ", "#    ", "#####"],
}

FONT_FIRST = 0x20
FONT_LAST = 0x5A  # 'Z'


def build_font_inc(path):
    lines = ["@ Generated by msrthumb_build.py - do not edit.", "font_data:"]
    for code in range(FONT_FIRST, FONT_LAST + 1):
        ch = chr(code)
        rows = GLYPHS.get(ch)
        if rows is None:
            rows = ["     "] * 7
        out = []
        for r in rows:
            v = 0
            for i, c in enumerate(r):
                if c == '#':
                    v |= 0x80 >> i
            out.append(v)
        out.append(0)  # 8th row: descender space
        lines.append("    .byte " + ", ".join("0x%02X" % b for b in out)
                     + "   @ '%s'" % (ch if ch != ' ' else 'SP'))
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


# ---------------------------------------------------------------------------
# Cartridge header
# ---------------------------------------------------------------------------
# The Nintendo logo bitmap, required by the BIOS boot check on real hardware.
# Identical in every commercial and homebrew GBA ROM (devkitARM ships the same
# 156 bytes in its crt0); sha1 17daa0fec02fc33c0f6abb549a8b80b6613b48ee.
NINTENDO_LOGO = bytes.fromhex(
    "24ffae51699aa2213d84820a84e409ad11248b98c0817f21a352be199309ce20"
    "10464a4af82731ec58c7e83382e3cebf85f4df94ce4b09c194568ac01372a7fc"
    "9f844d73a3ca9a615897a327fc039876231dc7610304ae56bf38840040a70efd"
    "ff52fe036f9530f197fbc08560d68025a963be03014e38e2f9a234ffbb3e0344"
    "780090cb88113a9465c07c6387f03cafd625e48b380aac7221d4f807"
)
assert len(NINTENDO_LOGO) == 156
assert hashlib.sha1(NINTENDO_LOGO).hexdigest() == \
    "17daa0fec02fc33c0f6abb549a8b80b6613b48ee"

TITLE = b"MSRTHUMB"      # 12 bytes, zero padded
GAME_CODE = b"MSRT"      # 4
MAKER_CODE = b"00"       # 2


def fix_header(rom: bytearray):
    rom[0x04:0xA0] = NINTENDO_LOGO
    rom[0xA0:0xAC] = TITLE.ljust(12, b"\0")
    rom[0xAC:0xB0] = GAME_CODE
    rom[0xB0:0xB2] = MAKER_CODE
    rom[0xB2] = 0x96          # fixed value
    rom[0xB3] = 0x00          # main unit code
    rom[0xB4] = 0x00          # device type
    rom[0xB5:0xBC] = b"\0" * 7
    rom[0xBC] = 0x00          # software version
    chk = 0
    for b in rom[0xA0:0xBD]:
        chk = (chk - b) & 0xFF
    rom[0xBD] = (chk - 0x19) & 0xFF
    rom[0xBE:0xC0] = b"\0\0"


# ---------------------------------------------------------------------------
# Encoding self-check: the probe's payload words must decode to exactly the
# instructions the test's legend claims, under BOTH decoders.
# ---------------------------------------------------------------------------
PAYLOAD_CHECK = [
    # (word, expected ARM mnemonic prefix, expected thumb-lo, expected thumb-hi)
    (0x35813404, "strcc", "addcc" if False else "add", "add"),
    (0x37813609, "strcc", "add", "add"),
    (0xE0A04700, "adc", "bx", None),
]


def disassemble(word: int, thumb: bool):
    """Disassemble one 32-bit word as ARM, or its two halfwords as Thumb."""
    bin_path = os.path.join(HERE, "_dis.bin")
    with open(bin_path, "wb") as f:
        f.write(word.to_bytes(4, "little"))
    out = subprocess.run(
        ["arm-none-eabi-objdump", "-D", "-b", "binary", "-m", "arm",
         "-M", "force-thumb" if thumb else "reg-names-std", bin_path],
        check=True, capture_output=True, text=True).stdout
    os.remove(bin_path)
    res = []
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        head = parts[0].strip().rstrip(":").strip()
        try:
            int(head, 16)
        except ValueError:
            continue
        res.append("\t".join(parts[2:]).strip())
    return res


def main():
    build_font_inc(os.path.join(HERE, "msrthumb_font.inc"))

    src = os.path.join(HERE, "msrthumb.s")
    obj = os.path.join(HERE, "msrthumb.o")
    gba = os.path.join(HERE, "msrthumb.gba")

    elf = os.path.join(HERE, "msrthumb.elf")
    subprocess.run(["arm-none-eabi-as", "-mcpu=arm7tdmi", "-I", HERE,
                    "-o", obj, src], check=True)
    # Must be linked, not just assembled: the probe table and the `ldr rN,=label`
    # literals need absolute cart addresses, and a bare .o resolves labels
    # relative to the section (which sends `mov pc, r6` into the BIOS).
    subprocess.run(["arm-none-eabi-ld", "-Ttext=0x08000000", "-e", "_start",
                    "--no-warn-rwx-segments", "-o", elf, obj], check=True)
    subprocess.run(["arm-none-eabi-objcopy", "-O", "binary", elf, gba],
                   check=True)

    rom = bytearray(open(gba, "rb").read())
    if len(rom) < 0xC0:
        rom.extend(b"\0" * (0xC0 - len(rom)))
    fix_header(rom)
    # Pad to 32 KiB: some flashcarts and linkers dislike sub-kilobyte images.
    if len(rom) < 32768:
        rom.extend(b"\0" * (32768 - len(rom)))
    open(gba, "wb").write(bytes(rom))
    os.remove(obj)
    os.remove(elf)

    print("wrote %s (%d bytes)" % (gba, len(rom)))
    print()
    print("payload word decode check (both decoders):")
    for word, _, _, _ in PAYLOAD_CHECK:
        a = disassemble(word, thumb=False)
        t = disassemble(word, thumb=True)
        print("  0x%08X" % word)
        print("      ARM   : %s" % (a[0] if a else "?"))
        print("      THUMB : lo=%-22s hi=%s"
              % (t[0] if t else "?", t[1] if len(t) > 1 else "?"))


if __name__ == "__main__":
    sys.exit(main())
